[build]
command = "DEBUG=* eleventy"
publish = "_site"

[[redirects]]
from = "/2020"
to = "/blog/2020"

[[redirects]]
from = "/2019"
to = "/blog/2019"

[[redirects]]
from = "/2018"
to = "/blog/2018"

[[redirects]]
from = "/2016"
to = "/blog/2016"
